### ISSUE TITLE
Upload metadata.tsv for downstream use

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/seasonal-flu#107]
You already upload raw fasta to AWS in `rule upload_sequences`.

It would be useful for our <https://github.com/neherlab/flu_frequencies> repo to be able to download metadata.tsv as produced by your `rule parse`.

I will duplicate your parse for now, but in the future it would be nice to reduce code duplication and parse in one place.

Is there a reason you are currently only uploading the raw data not the parsed one?

**Comment by huddlej** [comment]
Thank you for asking about this, @corneliusroemer. There's no good reason to not upload sequences.fasta and metadata.tsv now. The only reason I didn't originally was because I wasn't sure whether the S3 uploads would be useful or how they would work. Now that they are working, we can upload the more useful downstream files.
