### ISSUE TITLE
H3N2 NA aa length is wrong 

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/seasonal-flu#98]
### Current Behavior

The H3N2 NA build on nextstrain.org contains a mutation that's not within the range for selection. There is a major mutation (I469T) that is not selectable by the 'Color By' option. The range is 1 - 468. Note the mutation is outside this range (I469T)

### Expected behavior

This link should work:
https://nextstrain.org/flu/seasonal/h3n2/na/2y?branchLabel=aa&c=gt-NA_469

But nextstrain will return the standard tree. See NODE_0001125 for the mutation I am referring to.

### Possible solution
Change the range to 1 - 469

**Comment by ammaraziz** [comment]
Out of interest is this an auspice setting or an issue with augur output?

**Comment by joverlee521** [comment]
Hi @ammaraziz, thank you for reporting this bug! 

The root of the problem seems to be the [CDS coordinates in our workflow's H3N2 NA reference](https://github.com/nextstrain/seasonal-flu/blob/master/config/reference_h3n2_na.gb#L47). The current coordinates are `4..1410`, but the full coordinates should be `4..1413` based on the [record in GenBank](https://www.ncbi.nlm.nih.gov/nuccore/CY113679.1). 

This reference is passed to the `augur translate` command via the `--reference-sequence` option in the workflow. The [features parsed from the reference](https://github.com/nextstrain/augur/blob/53fed2dcbb8619efbf76766e2b92558e201cf09a/augur/translate.py#L382-L387) are used to generate the genome annotations which are ultimately exported by `augur export v2` as the `meta.genome_annotations` in the main Auspice JSON file. 

Within Auspice, the range displayed is based on the [gene length calculated from the `meta.genomeAnnotations`](https://github.com/nextstrain/auspice/blob/603495ddeb998dcb96d7f25a87abbb0b2166e7de/src/actions/recomputeReduxState.js#L311-L317). With the current CDS coordinates, this is calculated as `Math.floor((1410 - 4) / 3)`, which is 468.

**Comment by joverlee521** [comment]
For now, I've manually edited the genome annotations in the current seasonal flu builds so you can use the color-by option. 
Once #99 is merged, future builds should be fixed as well.

**Comment by tsibley** [comment]
Notably, even in the copy we have with the bad coordinates, the `translation` field for that CDS _is_ the correct length (469).

This also raises the question of if any of the other reference files are subtly wrong?

**Comment by ammaraziz** [comment]
Thank you for the quick fix @joverlee521. I was trying to track where the issue was coming from, so thank you for explaining.

@tsibley Good point. I visually inspected (using UGENE software) HA/NA segments for the 4 subtypes. From how the range is calculated, the stop codon needs to be included. 

The other NA gb files are correct (except the aforementioned issue with H3)
H3HA short by 3 for HA2

Thank you for fixing this issue!

**Comment by huddlej** [comment]
Fixed by https://github.com/nextstrain/seasonal-flu/pull/99
